[package]
name = "screenctl"
version = "0.1.0"
authors = ["Jon Valdés"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddc = "0.2.2"
ddc-winapi = "0.2.0"
clap = "2.33.3"
